//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gelen_kutusu
    {
        public string kullanici_adi { get; set; }
        public Nullable<int> mesaj { get; set; }
    }
}
