//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanici_list()
        {
            this.mesajlar = new HashSet<mesajlar>();
        }
    
        public int ID_kullanici { get; set; }
        public string kullanici_adi_u { get; set; }
        public string sifre { get; set; }
        public string IP { get; set; }
        public Nullable<bool> durum { get; set; }
        public string ID_mesajlar { get; set; }
        public string ID_unutulan_sifre { get; set; }
    
        public virtual unutulan_sifre unutulan_sifre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajlar> mesajlar { get; set; }
    }
}
