//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajlar
    {
        public int ID_g { get; set; }
        public string kullanici_adi_g { get; set; }
        public string kullanici_adi_a { get; set; }
        public string ID_alici { get; set; }
        public int mesaj_no { get; set; }
        public string mesaj { get; set; }
        public string message_type { get; set; }
    
        public virtual kullanici_list kullanici_list { get; set; }
    }
}
