//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RCEntities : DbContext
    {
        public RCEntities()
            : base("name=RCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gelen_kutusu> gelen_kutusu { get; set; }
        public virtual DbSet<kullanici_list> kullanici_list { get; set; }
        public virtual DbSet<mesajlar> mesajlar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unutulan_sifre> unutulan_sifre { get; set; }
        public virtual DbSet<yonetici_giris> yonetici_giris { get; set; }
    }
}
