//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class yonetici_giris
    {
        public int ID_y_giris { get; set; }
        public string kullanici_adi_a { get; set; }
        public string sifre { get; set; }
        public string tur { get; set; }
    }
}
